name: Build iOS IPA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          brew update
          brew install xcodegen
      - name: Generate project file
        run: xcodegen generate
      - name: Build & Archive
        run: |
          xcodebuild archive -project tvbox.xcodeproj -scheme tvbox -destination "generic/platform=iOS" -archivePath ./build/tvbox.xcarchive
          mkdir -p ./export
          xcodebuild -exportArchive -archivePath ./build/tvbox.xcarchive -exportOptionsPlist <(echo '<?xml version="1.0"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>development</string><key>signingStyle</key><string>manual</string><key>signingCertificate</key><string>iOS Developer</string></dict></plist>') -exportPath ./export
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: TVBox-iOS
          path: export/*.ipa